### PR TITLE
Hotfix/const correct

### LINKED ISSUE #26: operator==() in EndfTk record implemetations should be const
The operator==() functions implemented for the list and tab1 are not const. These are the only ones that we actually looked at but the other ones should be checked as well (you never know).

### PR DESCRIPTION
**Pull request by apmccartney**
closes #26

### CODE REVIEW

**Comment by jlconlin** [comment]
Why the change to the underlying map implementation?

**Comment by apmccartney** [comment]
Performance

**Comment by apmccartney** [comment]
Don't merge, tests to come

**Comment by whaeck** [comment]
I was going to wait to ask you about the coverage results before merging it anyway :-)

**Pull request merged**
